### ISSUE TITLE
Uncaught TypeError: Cannot read property 'compositionInProgress' of null

### ISSUE THREAD

**Issue by TheSeamau5** [atom-community/autocomplete-plus#241]
[Enter steps to reproduce below:]

1. [See this issue](https://github.com/atom/atom/issues/5402)
2. Now editor is completely frozen and unusable. Any attempts to press a keyboard key triggers this error :(

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.0.12

### Stack Trace

Uncaught TypeError: Cannot read property 'compositionInProgress' of null

```
At /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:234

TypeError: Cannot read property 'compositionInProgress' of null
  at AutocompleteManager.module.exports.AutocompleteManager.bufferChanged (/Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:234:30)
  at /Users/hassanhayat/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:165:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:122:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1178:26)
  at [object Object].module.exports.React.createClass.onTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:647:30)
  at HTMLDivElement.boundMethod (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

### Commands

```
     -6:41.4 editor:indent (atom-text-editor.editor.is-focused)
     -6:40.9 editor:newline (atom-text-editor.editor.is-focused)
  4x -6:40.1 core:backspace (atom-text-editor.editor.is-focused)
     -6:37.8 core:move-left (atom-text-editor.editor.is-focused)
     -6:37.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:31.7 autocomplete-plus:confirm (input)
  5x -6:28.7 core:backspace (atom-text-editor.editor.is-focused)
     -5:54.4 core:move-left (atom-text-editor.editor.is-focused)
     -5:40.1 core:backspace (atom-text-editor.editor.is-focused)
     -5:39.3 core:move-right (atom-text-editor.editor.is-focused)
     -5:33.1 core:save (atom-text-editor.editor.is-focused)
     -5:31.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -4:36.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.6 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.2 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:00.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gjslint",
      "linter",
      "linter-dartanalyzer"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-typescript-tools, v0.6.2
autoclose-html, v0.14.0
autocomplete-plus, v2.0.12
better-language-dart, v1.0.1
color-picker, v1.4.4
dart-tools, v0.8.5
language-ada, v0.2.0
language-coq, v0.1.0
language-css-plus, v0.3.0
language-d, v3.0.1
language-elm, v0.4.1
language-glsl, v0.2.2
language-julia, v2.0.0
language-opencl, v0.1.0
language-pegjs, v0.5.0
language-r, v0.1.1
language-sml, v0.2.0
language-typescript, v0.15.0
language-x86, v0.1.0
linter-csslint, v0.0.11
minimap, v4.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Please update your version of Atom to `0.177.0` or later.

**Comment by TheSeamau5** [comment]
Cool. Thanks. I updated my version of Atom and I haven't encountered this error yet. I'll let you know if this ever comes up again. Thanks for your help.

**Comment by TheSeamau5** [comment]
[The issue that I've created that references this issue](https://github.com/atom/atom/issues/5437) is caused the same way than this issue. I recommend re-opening this issue as they seem related. 

From the error, it would seem that there is some sort of unchecked null and this unchecked null could be seeping into all sorts of places.

**Comment by TheSeamau5** [comment]
Also, it is important to note that autocomplete-plus was among the packages being updated while I went back to the code and tried typing some code (where autocomplete-plus was being used)
