### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by ghost** [atom-community/autocomplete-plus#252]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'split' of null
  at Function.module.exports.Range.fromText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/range.js:40:19)
  at TextBuffer.module.exports.TextBuffer.buildPatch (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:523:24)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:501:20)
  at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app/src/selection.js:446:43)
  at /usr/share/atom/resources/app/src/text-editor.js:773:31
  at /usr/share/atom/resources/app/src/text-editor.js:812:27
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1181:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:805:19)
  at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:770:21)
  at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /home/jess/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:208:15
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1181:26)
  at AutocompleteManager.module.exports.AutocompleteManager.replaceTextWithMatch (/home/jess/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:203:13)
  at AutocompleteManager.replaceTextWithMatch (/home/jess/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.confirm (/home/jess/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:168:6)
  at /home/jess/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirm (/home/jess/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:50:14)
  at SuggestionList.confirm (/home/jess/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at autocomplete-suggestion-list.SuggestionListElement.confirmSelection (/home/jess/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:87:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirmSelection (/home/jess/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:44:14)
  at atom-text-editor.<anonymous> (/home/jess/.atom/packages/autocomplete-plus/lib/suggestion-list.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:58.6 autocomplete-plus:confirm (atom-text-editor.editor.autocomplete-active)
  3x -0:56.6 core:backspace (atom-text-editor.editor.autocomplete-active)
     -0:52.7 application:new-file (atom-text-editor.editor.autocomplete-active)
     -0:51.0 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
  4x -0:44.7 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:42.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
  4x -0:41.3 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:37.4 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
  9x -0:36.8 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:32.3 autocomplete-plus:confirm (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:32.3 snippets:expand (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:31.4 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:30.7 editor:newline-above (atom-text-editor.editor.autocomplete-active.is-focused)
  9x -0:28.9 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:01.3 autocomplete-plus:confirm (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:00.3 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Please update to the latest atom and autocomplete-plus versions and let us know if this is still an issue.
