### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by besser** [atom-community/autocomplete-plus#285]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:559

TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:559:38)
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:552:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1042:35)
  at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2432:33)
  at Cursor.module.exports.Cursor.getScopeDescriptor (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:227:26)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/besser/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:110:27)
  at /Users/besser/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
     -0:45.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.9 core:undo (atom-text-editor.editor.is-focused)
     -0:41.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:38.9 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:36.7 core:move-right (atom-text-editor.editor.is-focused)
     -0:35.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:31.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.2 core:move-right (atom-text-editor.editor.is-focused)
     -0:29.1 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:26.5 core:undo (atom-text-editor.editor.is-focused)
  2x -0:23.5 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.7 core:cancel (atom-text-editor.editor.is-focused)
     -0:21.2 core:select-all (atom-text-editor.editor.is-focused)
     -0:18.4 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
 78x -0:12.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:00.9 core:redo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus"
    ],
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.3.0
autocomplete-plus, v2.2.0
color-picker, v1.4.4

# Dev
No dev packages
```

**Comment by benogle** [comment]
Can you give us steps to reproduce?

**Comment by joefitzgerald** [comment]
Please update to v2.5.0 and re-test.

**Comment by besser** [comment]
Ok, I will do more tests!

Thanks!

Roberto Mota Besser
rmbesser@gmail.com
