### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by youngking** [atom-community/autocomplete-plus#308]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.1.3

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:167

TypeError: undefined is not a function
  at FuzzyProvider.module.exports.FuzzyProvider.settingsForScopeDescriptor (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:167:27)
  at FuzzyProvider.module.exports.FuzzyProvider.getCompletionsForCursorScope (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:175:20)
  at FuzzyProvider.getCompletionsForCursorScope (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at FuzzyProvider.module.exports.FuzzyProvider.findSuggestionsForWord (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:152:34)
  at FuzzyProvider.findSuggestionsForWord (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at FuzzyProvider.module.exports.FuzzyProvider.requestHandler (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:63:20)
  at FuzzyProvider.requestHandler (/Users/youngking/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at /Users/youngking/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:128:63
  at Array.map (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/youngking/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:128:35)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/youngking/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/youngking/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:124:6)
  at /Users/youngking/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Update atom and your oackages. Then restart.

Please do this *always* before living issues.

**Comment by Cleecanth** [comment]
I'm still receiving this, even with the newest version of both Atom and Autocomplete-plus.

### Steps to reproduce:

1. Write a comment in any JS file (either /* or // )

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.4.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:91

TypeError: undefined is not a function
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.parseScopeChain (/Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:240:31)
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.getAll (/Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:94:21)
  at ProviderManager.module.exports.ProviderManager.providersForScopeDescriptor (/Users/Chris/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:45:24)
  at ProviderManager.providersForScopeDescriptor (/Users/Chris/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/Chris/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:124:34)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/Chris/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/Chris/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:121:6)
  at /Users/Chris/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
     -2:12.5 editor:newline (atom-text-editor.editor.is-focused)
     -2:03.7 core:copy (atom-text-editor.editor.is-focused)
     -2:01.3 core:select-down (atom-text-editor.editor.is-focused)
     -2:00.8 core:backspace (atom-text-editor.editor.is-focused)
     -2:00.3 core:paste (atom-text-editor.editor.is-focused)
     -1:58.4 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:53.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.2 core:save (atom-text-editor.editor.is-focused)
     -1:12.7 editor:newline (atom-text-editor.editor.is-focused)
 47x -1:02.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.6 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.5 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.2 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:02.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".idea",
      ".sass-cache",
      ".Thumbs-db",
      ".config",
      "*.rb",
      ".*cache"
    ],
    "disabledPackages": [
      "ConvertToUtf8Plus",
      "linter-scss-lint",
      "project-palette-finder"
    ],
    "themes": [
      "seti-ui",
      "brackets-syntax"
    ],
    "projectHome": "/Users/Chris/Sites/"
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.4.0
atom-beautify, v0.21.4
atom-handlebars, v0.4.0
autocomplete-plus, v2.4.1
better-handlebars, v0.1.1
bezier-curve-editor, v0.6.6
brackets-syntax, v0.4.1
color-picker, v1.4.4
compare-files, v0.4.1
filetype-color, v0.1.4
function-name-in-status-bar, v0.2.6
indentation-indicator, v0.4.1
language-css-plus, v0.3.0
language-slim, v0.3.0
preview-tabs, v0.1.6
project-manager, v1.15.5
recent-files, v0.3.0
seti-ui, v0.6.3
slash-closer, v0.7.1
soft-wrap-indicator, v0.5.1
svg-preview, v0.5.1
tabs-to-spaces, v0.8.1
toolbar, v0.0.11
toolbar-main, v0.0.5

# Dev
No dev packages
```

**Comment by jakubhruby** [comment]
I experience the same issue, also with newest versions of both Ato and all my packages
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.4.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\jhruby\AppData\Local\atom\app-0.187.0\resources\app\node_modules\scoped-property-store\lib\scoped-property-store.js:240

TypeError: undefined is not a function
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.parseScopeChain (C:\Users\jhruby\AppData\Local\atom\app-0.187.0\resources\app\node_modules\scoped-property-store\lib\scoped-property-store.js:240:31)
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.getAll (C:\Users\jhruby\AppData\Local\atom\app-0.187.0\resources\app\node_modules\scoped-property-store\lib\scoped-property-store.js:94:21)
  at ProviderManager.module.exports.ProviderManager.providersForScopeDescriptor (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\provider-manager.coffee:45:24)
  at ProviderManager.providersForScopeDescriptor (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\provider-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:124:34)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:121:6)
  at C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1

```

### Commands

```
  6x -5:59.3 core:backspace (atom-text-editor.editor)
  2x -4:27.2 editor:delete-to-beginning-of-word (atom-text-editor.editor)
  2x -4:22.6 core:backspace (atom-text-editor.editor)
  5x -4:17.4 editor:delete-to-beginning-of-word (atom-text-editor.editor)
     -3:56.0 editor:consolidate-selections (atom-text-editor.editor)
     -3:56.0 core:cancel (atom-text-editor.editor)
     -3:54.8 core:save (atom-text-editor.editor)
     -3:07.2 core:move-down (atom-text-editor.editor)
     -3:06.9 docblockr:parse-enter (atom-text-editor.editor)
     -3:06.8 editor:newline (atom-text-editor.editor)
     -3:03.9 core:backspace (atom-text-editor.editor)
     -3:03.5 snippets:next-tab-stop (atom-text-editor.editor)
     -3:03.5 snippets:expand (atom-text-editor.editor)
     -3:03.5 docblockr:parse-tab (atom-text-editor.editor)
     -3:03.5 editor:indent (atom-text-editor.editor)
  2x -0:11.6 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.2
color-picker, v1.4.4
docblockr, v0.6.3
git-blame, v0.4.0
git-history, v2.3.0
highlight-line, v0.10.1
jsdoc, v0.9.0
jshint, v1.3.0
language-htaccess, v0.0.1
local-history, v2.2.2
minimap, v4.5.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
open-last-project, v0.3.4
pretty-json, v0.3.2
project-manager, v1.15.5
revert-buffer, v0.5.0
slash-closer, v0.7.1
sync-settings, v0.2.2
tab-history, v0.4.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Does this problem still exist, after upgrading to `v2.5.0`? This removes the scoped-property-store, which is the source of the error you pasted @jakubhruby.

**Comment by jakubhruby** [comment]
Still there:

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\scope-helpers.coffee:6

TypeError: undefined is not a function
  at parseScopeChain (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\scope-helpers.coffee:6:27)
  at selectorForScopeChain (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\scope-helpers.coffee:11:14)
  at selectorsMatchScopeChain (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\scope-helpers.coffee:18:3)
  at ProviderMetadata.module.exports.ProviderMetadata.matchesScopeChain (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\provider-metadata.coffee:17:23)
  at ProviderManager.module.exports.ProviderManager.providersForScopeDescriptor (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\provider-manager.coffee:47:27)
  at ProviderManager.providersForScopeDescriptor (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\provider-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:124:34)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:121:6)
  at C:\Users\jhruby\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1

```

### Commands

```
  4x -1:34.4 core:backspace (atom-text-editor.editor)
     -1:32.3 docblockr:parse-enter (atom-text-editor.editor)
     -1:32.3 editor:newline (atom-text-editor.editor)
     -1:31.1 core:save (atom-text-editor.editor)
     -1:28.8 editor:consolidate-selections (atom-text-editor.editor)
     -1:28.8 core:cancel (atom-text-editor.editor)
     -1:28.6 editor:consolidate-selections (atom-text-editor.editor)
     -1:28.6 core:cancel (atom-text-editor.editor)
     -1:27.6 settings-view:open (atom-text-editor.editor)
  2x -0:07.0 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.5.0
color-picker, v1.4.4
docblockr, v0.6.3
highlight-line, v0.10.1
jsdoc, v0.9.0
jshint, v1.3.0
language-htaccess, v0.0.1
local-history, v2.2.2
minimap, v4.6.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
open-last-project, v0.3.4
pretty-json, v0.3.2
project-manager, v1.15.5
revert-buffer, v0.5.0
slash-closer, v0.7.1
sync-settings, v0.2.2
tab-history, v0.4.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
@jakubhruby can you upgrade to 2.6.0 and try again? This one should throw a new, more descriptive error. In addition to the red error notification, it will log to the console with the json and the object itself.

I am still unable to reproduce this, and it doesnt make much sense. My thoughts: https://github.com/atom-community/autocomplete-plus/pull/321#issuecomment-83153100

**Comment by jakubhruby** [comment]
The bug seems to be gone, thanks.

**Comment by benogle** [comment]
Interesting. I just changed the error it would throw in this situation. I'll leave this open for a little while. If anyone makes it happen again, please the error report here.

**Comment by EllieAdam** [comment]
Since I installed autocomplete-plus my txt editor won't work only give me error. Links send me on this page. How I uninstall autocomplete? it is not giving me any option.
Thanks

**Comment by benogle** [comment]
@EllieAdam If you are not on the latest version of atom or autocomplete-plus, please upgrade both.

If you are on the latest versions, can you copy the error with the clipboard button, and paste it in here?

**Comment by michaellenahan** [comment]
Got this error just now. Atom editor and all packages up-to-date

[Enter steps to reproduce below:]

1. Install autocomplete-plus
2. Shift focus to a tab containing html

**Atom Version**: 0.184.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.8.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/michael/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:55

TypeError: undefined is not a function
  at FuzzyProvider.module.exports.FuzzyProvider.updateCurrentEditor (/home/michael/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:55:45)
  at FuzzyProvider.updateCurrentEditor (/home/michael/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at /home/michael/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:33:8

```

### Commands

```
     -5:29.3 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:22.3 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -4:15.2 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:05.0 autocomplete:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:57.7 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -3:52.8 core:backspace (atom-text-editor.editor.mini)
  2x -3:48.9 core:confirm (atom-text-editor.editor.mini)
     -1:20.7 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:19.2 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:19.2 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:19.1 editor:indent (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:15.3 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:15.3 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:12.7 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:12.3 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:06.5 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
project-manager, v1.15.5
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
> Atom editor and all packages up-to-date

Well that's not the case because atom is 0.189.0.

**Comment by noseglid** [comment]
I had this. Updated. Now it works.
