### ISSUE TITLE
Failed to activate the autocomplete-plus package

### ISSUE THREAD

**Issue by EatMyGeek** [atom-community/autocomplete-plus#312]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.4
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.4.1

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom 2.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/edition/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:7:7)
    at Object.<anonymous> (/Users/edition/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:514:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom 2.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "rain-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.1
file-icons, v1.5.1
minimap, v4.4.0
monokai, v0.12.0
rain-ui, v0.3.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Seems like you might have had network issues when installing the package. Could you uninstall it and reinstall it?

**Comment by joefitzgerald** [comment]
Is this issue still present for you, after reinstalling the package?

**Comment by jinmatt** [comment]
issue resolved after reinstalling the package
