### ISSUE TITLE
Failed to load the es-navigation package

### ISSUE THREAD

**Issue by huwmongoose** [atom-community/autocomplete-plus#339]
[Enter steps to reproduce below:]

1. just opened a txt file
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.6.0

### Stack Trace

Failed to load the es-navigation package

```
At Cannot find module 'escope'

Error: Cannot find module 'escope'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\Huw\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (C:\Users\Huw\.atom\packages\es-navigation\build\parse.js:13:29)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (C:\Users\Huw\AppData\Local\atom\app-0.187.0\resources\app\src\babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "autocomplete-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
compare-files, v0.4.1
emmet, v2.3.4
es-navigation, v0.1.5
highlight-line, v0.10.1
omnisharp-atom, v0.2.1
view-tail-large-files, v0.1.13
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update to the latest version of Atom and autocomplete-plus. Please also verify that you are not experiencing network issues during installation.

**Comment by joefitzgerald** [comment]
Closing due to no response.
