### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('type parameter') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by patrickjtoy** [atom-community/autocomplete-plus#355]
[Enter steps to reproduce below:]

1. create function w/o type arguments (e.g. myFunc(myArg) {})
2. add single type argument (e.g. myFunc<r>(myArg): r {})
3. crashed with below info

**Atom Version**: 0.189.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.8.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('type parameter') contains HTML space characters, which are not valid in tokens.

```
At atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:156

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('type parameter') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at autocomplete-suggestion-list.SuggestionListElement.renderItem (.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:156:26)
  at autocomplete-suggestion-list.SuggestionListElement.renderItems (.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:129:6)
  at .atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:67:35
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (AppData\Local\atom\app-0.189.0\resources\app\src\view-registry.js:159:9)
  at AppData\Local\atom\app-0.189.0\resources\app\src\view-registry.js:3:61

```

### Commands

```
     -1:52.4 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  6x -1:38.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.8 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -1:28.1 typescript:autocomplete (atom-text-editor.editor.is-focused)
     -1:28.1 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:23.1 typescript:autocomplete (atom-text-editor.editor.is-focused)
     -1:23.1 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:16.8 core:move-left (atom-text-editor.editor.is-focused)
     -1:16.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:57.8 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  3x -0:45.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:08.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:02.0 core:move-left (atom-text-editor.editor.is-focused)
 15x -0:01.2 core:select-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-syntax"
    ],
    "projectHome": "projectHome"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v2.6.1
autocomplete-plus, v2.8.0
base16-ocean-dark-syntax, v1.0.1
git-plus, v4.4.10
language-cshtml, v0.1.0
last-cursor-position, v0.7.0
linter, v0.12.0
minimap, v4.7.5
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by patrickjtoy** [comment]
This issue is no longer reproducible, closing.
