### ISSUE TITLE
variable @syntax-color-variable is undefined

### ISSUE THREAD

**Issue by echantigny** [atom-community/autocomplete-plus#365]
1. Just tried to install it.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the autocomplete-plus package

```
At variable @syntax-color-variable is undefined

Error
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:346:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:436:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:435:59)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:186:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  2x -9:50.2 core:backspace (div.settings-view.pane-item)
     -8:18.0 core:confirm (atom-text-editor.editor.mini)
     -7:28.0 core:undo (atom-text-editor.editor)
     -7:21.7 core:save (atom-text-editor.editor)
  4x -7:02.6 core:backspace (atom-text-editor.editor)
     -6:58.8 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0

# Dev
No dev packages
```

**Comment by echantigny** [comment]
This was fixed by updating Atom to latest version.  Sorry
