### ISSUE TITLE
Failed to activate the autocomplete-plus package

### ISSUE THREAD

**Issue by ariesfigured** [atom-community/autocomplete-plus#370]
**Atom Version:** 0.189.0
**System:** Mac OS X 10.10.2
**Thrown From:** autocomplete-plus package, v2.9.0

### Stack Trace

Failed to activate the autocomplete-plus package

```
Error: ENOENT: no such file or directory, open '/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:221:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:329:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:337:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:289:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:355:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:358:7)
  at Package.module.exports.Package.handleError (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:247:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

**Comment by joefitzgerald** [comment]
This error is weird. `provider.coffee` was removed weeks ago, and is not required by any files in the current version of the package. @benogle can you think of why this would occur?

**Comment by benogle** [comment]
@ariesfigured did this happen on update of the package? If not, when did it happen?

**Comment by ariesfigured** [comment]
It first happened when I tried to update it. I tried uninstalling it then installing again and the error still persists.

**Comment by benogle** [comment]
Do you have any providers installed that are requiring provider from autocomplete-plus? Can you remove `~/.atom/packages/autocomplete-plus` then install it again? Can you run `apm list` and paste the installed packages into this issue?

@joefitzgerald I dont know how the old providers used to work, could this be triggered by an old provider?

**Comment by ariesfigured** [comment]
Tried reinstalling today and it installed fine. Feel free to close this ticket.

**Comment by joefitzgerald** [comment]
> I dont know how the old providers used to work, could this be triggered by an old provider?

Yeah, I suppose that's possible. Old providers used to require `Provider` from the loaded autocomplete-plus package, but this was preventing activation of `autocomplete-plus`, not some provider. So it sounds like perhaps that is not the cause here.
