### ISSUE TITLE
I got this error at autocomplete

### ISSUE THREAD

**Issue by alexfqc** [atom-community/autocomplete-plus#376]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.9.0

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\vntalco\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/vntalco/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:8:7)
    at Object.<anonymous> (/C:/Users/vntalco/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:616:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\vntalco\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
css-color-underline, v1.0.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by benogle** [comment]
Does this happen when you restart atom? Or was this a one time fluke?

**Comment by joefitzgerald** [comment]
Closing due to no response.
