### ISSUE TITLE
Failed to activate the autocomplete-plus package

### ISSUE THREAD

**Issue by Gu5tavoC** [atom-community/autocomplete-plus#387]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.9.0

### Stack Trace

Failed to activate the autocomplete-plus package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/Gustavo/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:8:7)
    at Object.<anonymous> (/C:/Users/Gustavo/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:617:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Gustavo\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-youcompleteme, v0.1.1
autocomplete-plus, v2.9.0
minimap, v4.7.6
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please uninstall and reinstall the package. Please also verify that your network does not block github.com or npmjs.com and that you are not experiencing network issues when you perform the installation.

**Comment by Manthravadi** [comment]
I am also seeing this error at my office which is behind a proxy. I cloned the git repository into the C:\Users\<Username>\.atom\packages directory and then used npm install autocomplete-plus in order to install it. When I opened Atom, I got this error!

**Comment by blooker20** [comment]
Same for me

**Comment by Nick-us** [comment]
Same for me. Trouble for me too. TODAY

**Comment by DMB81** [comment]
Same here. My network blocks neither of the above sites. 
Reinstallation does not solve the problem.
