### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by albanm** [atom-community/autocomplete-plus#433]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.19.0-15-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:116

TypeError: Cannot read property 'length' of null
  at /home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:116:29
  at /home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:175:13
  at Array.forEach (native)
  at autocomplete-suggestion-list.SuggestionListElement.renderItems (/home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:98:11)
  at autocomplete-suggestion-list.SuggestionListElement.itemsChanged (/home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:47:6)
  at autocomplete-suggestion-list.SuggestionListElement.attachedCallback (/home/alban/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:16:6)
  at OverlayManager.module.exports.OverlayManager.renderOverlay (/usr/share/atom/resources/app/src/overlay-manager.js:42:24)
  at OverlayManager.module.exports.OverlayManager.render (/usr/share/atom/resources/app/src/overlay-manager.js:19:16)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/usr/share/atom/resources/app/src/lines-component.js:149:71)
  at CallbackQueue.mixInto.notifyAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /usr/share/atom/resources/app/src/text-editor-component.js:313:28

```

### Commands

```
 28x -2:08.1 wheel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:03.5 editor:fold-selection (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:00.9 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -2:00.0 wheel (div.underlayer)
     -1:59.1 core:paste (atom-text-editor.editor.is-focused.autocomplete-active)
 71x -1:58.6 wheel (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:46.3 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
 44x -0:40.8 wheel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.6 core:delete (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:14.1 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
 21x -0:07.3 core:select-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.3 core:delete (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:02.7 core:select-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.4 core:delete (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.6 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
go-plus, v3.2.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-jscs, v1.10.0
linter-jshint, v0.1.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Please update your version of Atom to `0.194.0` or greater.

**Comment by joefitzgerald** [comment]
Also, please update autocomplete-plus and other packages to the latest version.

**Comment by albanm** [comment]
Ok, will do it.

Thanks.

2015-05-04 20:26 GMT+02:00 Joe Fitzgerald <notifications@github.com>:
