### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lostinplace** [atom-community/autocomplete-plus#443]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.13.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/cwheeler/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:112

TypeError: undefined is not a function
  at autocomplete-suggestion-list.SuggestionListElement.render (/Users/cwheeler/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:112:16)
  at autocomplete-suggestion-list.SuggestionListElement.itemsChanged (/Users/cwheeler/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:107:21)
  at autocomplete-suggestion-list.SuggestionListElement.attachedCallback (/Users/cwheeler/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:54:6)
  at OverlayManager.module.exports.OverlayManager.renderOverlay (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/src/overlay-manager.js:42:24)
  at OverlayManager.module.exports.OverlayManager.render (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/src/overlay-manager.js:19:16)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/src/lines-component.js:149:71)
  at CallbackQueue.mixInto.notifyAll (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /Users/cwheeler/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:313:28

```

### Commands

```
     -1:24.2 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:20.7 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:19.5 command-palette:toggle (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:16.5 core:move-down (atom-text-editor.editor.mini)
     -1:15.5 core:move-up (atom-text-editor.editor.mini)
     -1:15.3 core:confirm (atom-text-editor.editor.mini)
     -1:15.3 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.3 core:confirm (atom-text-editor.editor.mini)
     -0:22.2 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:00.9 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.5 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.13.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by benogle** [comment]
Please update to the latest version of atom.
